name: Build MacOS Installer
on: [push]
jobs:
  Build-MacOS-Installer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Build .dmg Installer
        run: "sh macOS/build.sh"
