name: Build MacOS Installer
on: [push]
jobs:
  Build-MacOS-Installer:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: uname -m
      - run: sysctl -n machdep.cpu.brand_string

      - name: Build .dmg Installer
        run: sh macOS/build.sh
