name: Build MacOS Installer
on: [push]
jobs:
  Build-MacOS-Installer:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Librsvg using Homebrew
        run: |
          brew update
          brew install librsvg

      - name: Build .dmg Installer
        run: sh macOS/build.sh
